In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from imblearn.over_sampling import SMOTE

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    f1_score,
    confusion_matrix,
    precision_recall_curve,
    auc
)

In [3]:
fraud_df = pd.read_csv("../data/processed/fraud_processed.csv")
credit_df = pd.read_csv("../data/processed/creditcard_processed.csv")

In [4]:
X_f = fraud_df.drop('class', axis=1)
y_f = fraud_df['class']

In [5]:
X_f = X_f.drop(columns=[
    'signup_time',
    'purchase_time',
    'device_id'
], errors='ignore')

In [6]:
Xf_train, Xf_test, yf_train, yf_test = train_test_split(
    X_f,
    y_f,
    test_size=0.2,
    random_state=42,
    stratify=y_f
)

In [7]:
imputer = SimpleImputer(strategy='median')

Xf_train = imputer.fit_transform(Xf_train)
Xf_test = imputer.transform(Xf_test)

c:\Users\cbe\Desktop\fraud\.venv\Lib\site-packages\sklearn\impute\_base.py:647: UserWarning: Skipping features without any observed values: ['prev_purchase_time']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\Users\cbe\Desktop\fraud\.venv\Lib\site-packages\sklearn\impute\_base.py:647: UserWarning: Skipping features without any observed values: ['prev_purchase_time']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(


In [8]:
smote = SMOTE(random_state=42)

Xf_train_res, yf_train_res = smote.fit_resample(
    Xf_train,
    yf_train
)

In [9]:
lr_fraud = LogisticRegression(max_iter=1000)
lr_fraud.fit(Xf_train_res, yf_train_res)

,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is '

In [10]:
yf_pred = lr_fraud.predict(Xf_test)
yf_prob = lr_fraud.predict_proba(Xf_test)[:, 1]

In [11]:
f1_fraud = f1_score(yf_test, yf_pred)

precision, recall, _ = precision_recall_curve(yf_test, yf_prob)
aucpr_fraud = auc(recall, precision)

cm_fraud = confusion_matrix(yf_test, yf_pred)

CREDIT CARD PIPELINE

In [12]:
X_c = credit_df.drop('Class', axis=1)
y_c = credit_df['Class']

In [13]:
Xc_train, Xc_test, yc_train, yc_test = train_test_split(
    X_c,
    y_c,
    test_size=0.2,
    random_state=42,
    stratify=y_c
)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

Xc_train['Amount'] = scaler.fit_transform(Xc_train[['Amount']])
Xc_test['Amount'] = scaler.transform(Xc_test[['Amount']])

In [15]:
Xc_train = imputer.fit_transform(Xc_train)
Xc_test = imputer.transform(Xc_test)

In [16]:
Xc_train = imputer.fit_transform(Xc_train)
Xc_test = imputer.transform(Xc_test)

In [17]:
Xc_train_res, yc_train_res = smote.fit_resample(
    Xc_train,
    yc_train
)

In [18]:
lr_credit = LogisticRegression(max_iter=1000)
lr_credit.fit(Xc_train_res, yc_train_res)

c:\Users\cbe\Desktop\fraud\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is '

In [19]:
yc_pred = lr_credit.predict(Xc_test)
yc_prob = lr_credit.predict_proba(Xc_test)[:, 1]

In [20]:
f1_credit = f1_score(yc_test, yc_pred)

precision, recall, _ = precision_recall_curve(yc_test, yc_prob)
aucpr_credit = auc(recall, precision)

cm_credit = confusion_matrix(yc_test, yc_pred)

In [21]:
results = pd.DataFrame({
    "Dataset": ["Fraud (E-commerce)", "Credit Card"],
    "F1 Score": [f1_fraud, f1_credit],
    "AUC-PR": [aucpr_fraud, aucpr_credit]
})

results

,Dataset,F1 Score,AUC-PR
0,Fraud (E-commerce),0.163912,0.095020
1,Credit Card,0.233766,0.732239


 Fraud dataset (VERY LOW PERFORMANCE)
 F1 = 0.16 (low)
 AUC-PR = 0.095 (extremely low)
 Interpretation:

Model is struggling badly to detect fraud
Likely predicting most cases as non-fraud (0)
SMOTE may not have fully captured fraud patterns
Why this happens:
High feature noise (device_id, IP, behavioral data)
Weak linear separability for Logistic Regression
Fraud patterns are complex + non-linear

Credit card dataset (OK performance)
F1 = 0.21 (still low but better)
AUC-PR = 0.75 (GOOD)

 Interpretation:

Model is actually learning signal
Credit dataset is much more structured (PCA features help)
Logistic Regression can capture some patterns

The credit card dataset achieved significantly higher AUC-PR compared to the e-commerce fraud dataset, indicating that PCA-transformed features provide a more separable structure for linear models. In contrast, the fraud dataset exhibits complex behavioral patterns that are not well captured by Logistic Regression..


 Random Forest Ensemble Model

Random Forest was selected as the ensemble model because it can capture non-linear fraud patterns and interactions between features that Logistic Regression may miss.

In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [23]:
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20],
    'min_samples_split': [2, 5]
}

rf_fraud = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)

grid_fraud = GridSearchCV(
    estimator=rf_fraud,
    param_grid=param_grid,
    scoring='f1',
    cv=3,
    n_jobs=-1
)

grid_fraud.fit(Xf_train_res, yf_train_res)

,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",RandomForestC...ndom_state=42)
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'max_depth': [10, 20], 'min_samples_split': [2, 5], 'n_estimators': [100, 200]}"
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion <scoring_api_overview>` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",'f1'
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",-1
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- an iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide <cross_validation>` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",3
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example<sphx_glr_auto_examples_model_selection_plot_grid_search_refit_callable.py>`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"verbose verbose: int, default=0Controls the verbo

In [27]:
print(grid_fraud.best_params_)

{'max_depth': 20, 'min_samples_split': 2, 'n_estimators': 200}


Interpretation
n_estimators = 200
The model performed best with 200 trees rather than 100.
More trees generally improve stability and predictive performance.
max_depth = 20
The model benefited from deeper trees.
This suggests fraud patterns are relatively complex and require more decision layers to separate fraud from legitimate transactions.
min_samples_split = 2
The model preferred splitting nodes as soon as possible.
This allows the trees to capture fine-grained fraud patterns.
The results indicate that a larger ensemble of deeper trees was more effective at capturing complex fraud patterns in the e-commerce transaction data.

In [28]:
best_rf_fraud = grid_fraud.best_estimator_

yf_pred_rf = best_rf_fraud.predict(Xf_test)
yf_prob_rf = best_rf_fraud.predict_proba(Xf_test)[:, 1]

In [29]:
from sklearn.metrics import (
    f1_score,
    confusion_matrix,
    precision_recall_curve,
    auc
)

f1_rf_fraud = f1_score(yf_test, yf_pred_rf)

precision, recall, _ = precision_recall_curve(
    yf_test,
    yf_prob_rf
)

aucpr_rf_fraud = auc(recall, precision)

cm_rf_fraud = confusion_matrix(
    yf_test,
    yf_pred_rf
)

print("Fraud RF F1:", f1_rf_fraud)
print("Fraud RF AUC-PR:", aucpr_rf_fraud)
print(cm_rf_fraud)

Fraud RF F1: 0.5233111322549953
Fraud RF AUC-PR: 0.5462578195820698
[[22726   650]
 [ 1354  1100]]


Improvement from the Logistic Regression

F1 Score

0.164 → 0.523
More than 3× improvement

AUC-PR

0.095 → 0.546
Nearly 6× improvement

This is a very strong improvement and exactly what we'd expect when moving from a linear model to an ensemble model for fraud detection.

 Confusion Matrix
 True Negatives (TN): 22,726
False Positives (FP): 650
False Negatives (FN): 1,354
True Positives (TP): 1,100

Recall=
TP+FN/TP

	​


Using the above values :

Recall=
1100+1354/1100 ≈ 44.8%
So the model catches about 45% of fraudulent transactions.

Precision

Precision tells us:

Of all transactions flagged as fraud, how many were actually fraud?

Precision=
TP+FP/TP

Using your values:

Precision=
1100+650/1100 ≈ 62.9%
	​
So when the model flags fraud, it is correct about 63% of the time.


Random Forest Performance (Fraud Dataset)

A Random Forest classifier was trained using SMOTE-balanced training data. Hyperparameter tuning was conducted using GridSearchCV with 3-fold cross-validation. The optimal configuration consisted of 200 trees, a maximum depth of 20, and a minimum split size of 2.

The Random Forest significantly outperformed the Logistic Regression baseline, achieving an F1-score of 0.523 and an AUC-PR of 0.546. Compared with the baseline model (F1-score = 0.164, AUC-PR = 0.095), the ensemble model demonstrated a substantially improved ability to identify fraudulent transactions.

The confusion matrix showed that the model correctly detected 1,100 fraudulent transactions while maintaining a relatively low false-positive count of 650 transactions. These results indicate that Random Forest is more effective at capturing complex fraud patterns than a linear classifier.

Credit Card Dataset

In [30]:
rf_credit = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)

grid_credit = GridSearchCV(
    estimator=rf_credit,
    param_grid=param_grid,
    scoring='f1',
    cv=3,
    n_jobs=-1
)

grid_credit.fit(
    Xc_train_res,
    yc_train_res
)

,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",RandomForestC...ndom_state=42)
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'max_depth': [10, 20], 'min_samples_split': [2, 5], 'n_estimators': [100, 200]}"
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion <scoring_api_overview>` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",'f1'
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",-1
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- an iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide <cross_validation>` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",3
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example<sphx_glr_auto_examples_model_selection_plot_grid_search_refit_callable.py>`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"verbose verbose: int, default=0Controls the verbo

In [31]:
best_rf_credit = grid_credit.best_estimator_

yc_pred_rf = best_rf_credit.predict(Xc_test)
yc_prob_rf = best_rf_credit.predict_proba(Xc_test)[:, 1]

In [32]:
f1_rf_credit = f1_score(
    yc_test,
    yc_pred_rf
)

precision, recall, _ = precision_recall_curve(
    yc_test,
    yc_prob_rf
)

aucpr_rf_credit = auc(
    recall,
    precision
)

cm_rf_credit = confusion_matrix(
    yc_test,
    yc_pred_rf
)

print("Credit RF F1:", f1_rf_credit)
print("Credit RF AUC-PR:", aucpr_rf_credit)
print(cm_rf_credit)

Credit RF F1: 0.8268156424581006
Credit RF AUC-PR: 0.8158234710423162
[[56641    10]
 [   21    74]]


Metrics Interpretation
True Positives (TP): 74
False Positives (FP): 10
False Negatives (FN): 21
True Negatives (TN): 56,641
Recall
Recall=
74+21/74 ≈ 77.9%

The model detects nearly 78% of fraudulent transactions.

Precision
Precision=
74+10/74 ≈ 88.1%

When the model flags a transaction as fraud, it is correct about 88% of the time.

This is a strong fraud detection model.

In [33]:
comparison = pd.DataFrame({
    'Dataset': [
        'Fraud',
        'Fraud',
        'Credit Card',
        'Credit Card'
    ],
    'Model': [
        'Logistic Regression',
        'Random Forest',
        'Logistic Regression',
        'Random Forest'
    ],
    'F1 Score': [
        f1_fraud,
        f1_rf_fraud,
        f1_credit,
        f1_rf_credit
    ],
    'AUC-PR': [
        aucpr_fraud,
        aucpr_rf_fraud,
        aucpr_credit,
        aucpr_rf_credit
    ]
})

comparison

,Dataset,Model,F1 Score,AUC-PR
0,Fraud,Logistic Regression,0.163912,0.095020
1,Fraud,Random Forest,0.523311,0.546258
2,Credit Card,Logistic Regression,0.233766,0.732239
3,Credit Card,Random Forest,0.826816,0.815823


In [43]:
import joblib

joblib.dump(
    best_rf_fraud,
    "../models/random_forest_fraud.pkl"
)

joblib.dump(
    best_rf_credit,
    "../models/random_forest_credit.pkl"
)

['../models/random_forest_credit.pkl']

In [39]:
import os

print(os.getcwd())

c:\Users\cbe\Desktop\fraud\fraud-detection\notebooks


Cross-Validation for Fraud Dataset

In [44]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)
f1_scores_fraud = cross_val_score(
    best_rf_fraud,
    Xf_train_res,
    yf_train_res,
    cv=cv,
    scoring='f1',
    n_jobs=-1
)

print("Fraud RF F1 Scores:", f1_scores_fraud)
print("Mean F1:", f1_scores_fraud.mean())
print("Std F1:", f1_scores_fraud.std())

Fraud RF F1 Scores: [0.93768858 0.93950924 0.93768056 0.93757569 0.93425567]
Mean F1: 0.9373419484244356
Std F1: 0.0017036246657153873


Cross-Validation Results (Fraud Dataset)

Five-fold Stratified Cross-Validation was performed on the SMOTE-balanced training data using the optimized Random Forest model. The model achieved a mean F1-score of 0.9373 with a standard deviation of 0.0017 across folds. The low standard deviation indicates highly consistent performance and suggests that the model generalizes reliably across different subsets of the training data.

In [45]:
aucpr_scores_fraud = cross_val_score(
    best_rf_fraud,
    Xf_train_res,
    yf_train_res,
    cv=cv,
    scoring='average_precision',
    n_jobs=-1
)

print("Fraud RF AP Scores:", aucpr_scores_fraud)
print("Mean AP:", aucpr_scores_fraud.mean())
print("Std AP:", aucpr_scores_fraud.std())

Fraud RF AP Scores: [0.98138325 0.98230125 0.98173295 0.98075599 0.98141668]
Mean AP: 0.9815180228488909
Std AP: 0.0005037360964645188


The Random Forest model achieved an exceptionally high cross-validated Average Precision (AUC-PR) score of 0.9815 ± 0.0005 across five Stratified K-Folds. This indicates that the model is highly effective at distinguishing between fraudulent and legitimate transactions under balanced training conditions. The extremely low standard deviation demonstrates consistent performance across all folds, suggesting strong stability and robustness. However, it is important to note that cross-validation was performed on SMOTE-resampled data, which may lead to slightly optimistic performance estimates compared to real-world imbalanced distributions.

Cross-Validation for Credit Card Dataset

In [46]:
f1_scores_credit = cross_val_score(
    best_rf_credit,
    Xc_train_res,
    yc_train_res,
    cv=cv,
    scoring='f1',
    n_jobs=-1
)

print("Credit RF F1 Scores:", f1_scores_credit)
print("Mean F1:", f1_scores_credit.mean())
print("Std F1:", f1_scores_credit.std())

Credit RF F1 Scores: [0.99993381 0.99988969 0.99984557 0.99981248 0.99979041]
Mean F1: 0.9998543909840839
Std F1: 5.1923538710375466e-05


The Random Forest model achieved near-perfect performance on the credit card fraud dataset, with a mean F1-score of 0.99985 ± 0.00005 across five Stratified Cross-Validation folds. The extremely high and stable scores indicate that the model is highly effective at distinguishing fraudulent transactions from legitimate ones within the transformed feature space. The very low standard deviation suggests consistent performance across different data splits, demonstrating strong model robustness. However, such near-perfect performance should be interpreted with caution, as the dataset consists of PCA-transformed features that may already encode strong separability between classes.

In [47]:
aucpr_scores_credit = cross_val_score(
    best_rf_credit,
    Xc_train_res,
    yc_train_res,
    cv=cv,
    scoring='average_precision',
    n_jobs=-1
)

print("Credit RF AP Scores:", aucpr_scores_credit)
print("Mean AP:", aucpr_scores_credit.mean())
print("Std AP:", aucpr_scores_credit.std())

Credit RF AP Scores: [0.99999948 0.99999931 0.9999967  0.9999164  0.99996908]
Mean AP: 0.9999761930630277
Std AP: 3.200773190102944e-05


The Random Forest model achieved an almost perfect Average Precision (AUC-PR) score of 0.99998 ± 0.00003 across five Stratified Cross-Validation folds on the credit card fraud dataset. This indicates that the model is extremely effective at ranking fraudulent transactions higher than legitimate ones, demonstrating near-complete separability in the feature space. The extremely low standard deviation further confirms that the model's performance is highly stable across different data splits. However, these results should be interpreted with caution due to the highly transformed PCA feature space, which may inherently provide strong class separability.

Model Comparison Summary

Fraud (E-commerce) Dataset

| Model               | F1 Score | AUC-PR |
| ------------------- | -------- | ------ |
| Logistic Regression | 0.164    | 0.095  |
| Random Forest       | 0.523    | 0.546  |


Credit Card Dataset

| Model               | F1 Score | AUC-PR |
| ------------------- | -------- | ------ |
| Logistic Regression | 0.213    | 0.754  |
| Random Forest       | 0.827    | 0.816  |


Cross-Validation Performance (Random Forest)

Fraud Dataset (SMOTE-balanced training data)
Mean F1: 0.9373 ± 0.0017
Mean AUC-PR: 0.9815 ± 0.0005
Credit Card Dataset
Mean F1: 0.99985 ± 0.00005
Mean AUC-PR: 0.99998 ± 0.00003

Observations
Random Forest consistently outperformed Logistic Regression across both datasets.
It achieved significantly higher recall and precision balance, which is critical in fraud detection.
The model captured non-linear relationships that Logistic Regression could not model.
Credit card dataset showed near-perfect separability due to PCA-transformed features.
E-commerce dataset was more realistic and challenging, resulting in lower but more practical performance.

Selected Model: Random Forest Classifier

Random Forest was selected as the best-performing model for both datasets based on the following reasons:

1.Superior Predictive Performance
Higher F1-score across both datasets
Higher AUC-PR, indicating strong performance under class imbalance
2.Robustness
Stable cross-validation performance with very low variance
Less sensitive to data distribution changes
3.Ability to Handle Complex Patterns
Captures non-linear relationships in transaction behavior
Performs well with mixed feature types (numerical + categorical)
4.Business Relevance
Reduces false negatives (missed fraud), which is critical in financial systems
Maintains acceptable false positive rates, reducing customer friction